version: "3"

services:
  tb_db:
    container_name: tb_db
    image: postgres:11.4
    tty: true
  tb_app:
    container_name: tb_app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - POSTGRESQL_HOST=mp_db
    volumes:
      - ./:/srv
    tty: true
    working_dir: /srv
    ports:
      - 8080:8080
    depends_on:
      - tb_db
    links:
      - tb_db
